import { create } from 'zustand';
const initialState = {
    data: [],
    total: 0,
    loading: false,
    loadingError: false,
    page: 1,
    pageSize: 25,
    searchText: '',
    selectedRow: null,
    cuentaFiltro: '',
    fechaDesde: '',
    fechaHasta: '',
    aplicadaFiltro: 'todas',
    cuentasBancarias: [],
};
export const useConciliacionBancariaStore = create((set) => ({
    ...initialState,
    setData: (data) => set({ data }),
    setTotal: (total) => set({ total }),
    setLoading: (loading) => set({ loading }),
    setLoadingError: (loadingError) => set({ loadingError }),
    setPage: (page) => set({ page }),
    setPageSize: (pageSize) => set({ pageSize }),
    setSearchText: (searchText) => set({ searchText }),
    setSelectedRow: (selectedRow) => set({ selectedRow }),
    setCuentaFiltro: (cuentaFiltro) => set({ cuentaFiltro }),
    setFechaDesde: (fechaDesde) => set({ fechaDesde }),
    setFechaHasta: (fechaHasta) => set({ fechaHasta }),
    setAplicadaFiltro: (aplicadaFiltro) => set({ aplicadaFiltro }),
    setCuentasBancarias: (cuentasBancarias) => set({ cuentasBancarias }),
    resetFiltros: () => set({
        cuentaFiltro: '',
        fechaDesde: '',
        fechaHasta: '',
        aplicadaFiltro: 'todas',
        searchText: '',
        page: 1,
    }),
}));
