import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import React from 'react';
import { Card, Divider } from 'antd';
import { formatNumber, toTitleCase } from '../utils/formats';
import { getMonedaSucursalActiva } from '../utils/moneda';
const TotalesCard = ({ subTotal, descuento, impuestos, total, retenciones, nota, alignRight = false, monedaSimbolo, monedaNombre, tasa, hideTitle = false, impuestosInformativos = [], pagado, pendiente, children, }) => {
    const monedaDefault = getMonedaSucursalActiva();
    const simboloFinal = monedaSimbolo || monedaDefault.simbolo;
    const nombreFinal = monedaNombre || monedaDefault.nombre;
    return (_jsxs(Card, { title: hideTitle ? null : _jsx("span", { style: { fontSize: 16, fontWeight: 600 }, children: "Totales" }), className: "paces-card", style: { marginBottom: 16 }, children: [_jsxs("div", { style: { display: 'flex', flexDirection: 'column', gap: 8, textAlign: alignRight ? 'right' : undefined }, children: [monedaSimbolo && tasa !== undefined && (_jsxs("div", { style: { display: 'flex', justifyContent: alignRight ? 'flex-end' : 'space-between', gap: 16 }, children: [!alignRight && _jsx("span", { className: "paces-text-secondary", children: "Moneda" }), _jsxs("span", { children: [toTitleCase(nombreFinal), " (", simboloFinal, " ", formatNumber(tasa ?? 1), ")"] })] })), _jsxs("div", { style: { display: 'flex', justifyContent: alignRight ? 'flex-end' : 'space-between', gap: 16, fontSize: 14 }, children: [!alignRight && _jsx("span", { className: "paces-text-secondary", children: "Subtotal" }), _jsx("span", { children: formatNumber(subTotal) })] }), _jsxs("div", { style: { display: 'flex', justifyContent: alignRight ? 'flex-end' : 'space-between', gap: 16, fontSize: 14 }, children: [!alignRight && _jsx("span", { className: "paces-text-secondary", children: "Descuento" }), _jsx("span", { children: formatNumber(descuento) })] }), _jsxs("div", { style: { display: 'flex', justifyContent: alignRight ? 'flex-end' : 'space-between', gap: 16, fontSize: 14 }, children: [!alignRight && _jsx("span", { className: "paces-text-secondary", children: "Impuestos" }), _jsx("span", { children: formatNumber(impuestos) })] }), impuestosInformativos && impuestosInformativos.length > 0 && impuestosInformativos.map((imp) => (_jsxs("div", { style: {
                            display: 'flex',
                            justifyContent: alignRight ? 'flex-end' : 'space-between',
                            gap: 16,
                            fontSize: 14,
                            paddingLeft: alignRight ? 0 : 24,
                        }, children: [!alignRight && _jsx("span", { className: "paces-text-secondary", children: imp.nombre }), _jsx("span", { children: formatNumber(imp.monto) })] }, imp.nombre))), retenciones !== undefined && (_jsxs("div", { style: { display: 'flex', justifyContent: alignRight ? 'flex-end' : 'space-between', gap: 16, fontSize: 14 }, children: [!alignRight && _jsx("span", { className: "paces-text-secondary", children: "Retenciones" }), _jsx("span", { children: formatNumber(retenciones) })] })), pagado !== undefined && (_jsxs("div", { style: { display: 'flex', justifyContent: alignRight ? 'flex-end' : 'space-between', gap: 16, fontSize: 14 }, children: [!alignRight && _jsx("span", { className: "paces-text-secondary", children: "Pagado" }), _jsx("span", { children: formatNumber(pagado) })] })), pendiente !== undefined && (_jsxs("div", { style: { display: 'flex', justifyContent: alignRight ? 'flex-end' : 'space-between', gap: 16, fontSize: 14 }, children: [!alignRight && _jsx("span", { className: "paces-text-secondary", children: "Pendiente" }), _jsx("span", { style: { fontWeight: 600, color: pendiente > 0 ? '#fa8c16' : undefined }, children: formatNumber(pendiente) })] }))] }), _jsx(Divider, { style: { margin: '12px 0' } }), _jsxs("div", { style: { display: 'flex', justifyContent: alignRight ? 'flex-end' : 'space-between', gap: 16, fontSize: 16, fontWeight: 700 }, children: [!alignRight && _jsx("span", { children: "Total" }), _jsxs("span", { style: { color: 'var(--paces-primary)' }, children: [simboloFinal, " ", formatNumber(total)] })] }), nota && (_jsxs(_Fragment, { children: [_jsx(Divider, { style: { margin: '12px 0' } }), _jsxs("div", { children: [_jsx("div", { style: { fontSize: 13, fontWeight: 600, marginBottom: 4, textAlign: alignRight ? 'right' : undefined }, className: "paces-text-secondary", children: "Notas" }), _jsx("div", { style: { fontSize: 13, whiteSpace: 'pre-wrap', lineHeight: 1.5, textAlign: alignRight ? 'right' : undefined }, className: "paces-text-dark", children: nota })] })] })), children] }));
};
export default TotalesCard;
